env: GitHub workflow 배포 확인단계 추가 (#10)
* env: github workflow 배포 확인 단계 추가

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -90,3 +90,21 @@ jobs:
 
             docker compose -f docker-compose.prod.yml up -d --remove-orphans --pull always
             docker image prune -af
+      
+       - name: Verify deployment
+        # 배포된 서비스가 완전히 뜨기까지 약간의 시간이 필요하므로, 15초 정도 기다립니다.
+        run: |
+          sleep 20
+          echo "Verifying deployment at https://b2bpoint.shop/health-check"
+          
+          
+          STATUS_CODE=$(curl -s -o /dev/null -w "%{http_code}" https://b2bpoint.shop/health-check)
+          
+          echo "Received status code: $STATUS_CODE"
+          
+          if [ "$STATUS_CODE" -ne 200 ]; then
+            echo "::error::Deployment verification failed with status code $STATUS_CODE"
+            exit 1
+          else
+            echo "Deployment verified successfully!"
+          fi
